[package]
name = "vectordb"
version = "0.1.0"
authors = ["BohuTANG <overred.shuttler@gmail.com>"]
edition = "2018"

[lib]
name = "vectordb"
path = "src/lib.rs"

[dependencies]
failure = "0.1.1"
sqlparser = "0.5"

